apiVersion: v1
kind: PersistentVolume
metadata: 
  name: ebs-static
spec:
  acceesModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  csi:
    driver: ebs.csi.aws.command
    fsType: ext4
    volumeHandle: vol-72a8f44214a23f64

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---
apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    purpose: ebs-static-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: perstistant-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: perstistant-storage
    PersistantVolumeCliam:
      claimeName: ebs-static

---
apiversion: v1
kind: Service
metadata:
  name: ebs-static
  lables:
    purpose: ebs-static-demo
    project: roboshop
spec:
  type: LoadBalencer
  selector:
    purpose: ebs-static-demo
    project: roboshop
  ports:
  - protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port
    



