apiVersion: storage.k8s.io/v1 # storage class
kind: StorageClass
metadata:
  name: roboshop-ebs
reclaimPolicy: Retain
provisioner: ebs.csi.aws.com
volumeBindMode: WaitForFirstConsumer # Disk will be created when pod is getting created.
