apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  accessMode:
  - ReadWriteOnce
  storageClassName: roboshop-ebs
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: pod
metadata:
  name: nginx
  labels:
    purpose: ebs-dynamic-demo
    project: roboshop
spec:
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c
  containers:
  - name: nginx
    image: nginx
    volumeMounts: # docker run -v host-path:container-path
    - name: perstistant-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: perstistant-storage
    PersistantVolumeCliam:
      claimName: ebs-dynamic