apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
  annotations:
    description: "This pod is created to demonstrate pod annotations"
    jenkins: "https://jenkins.com/build/job/roboshop-catalouge/3"
spec:
  containers:
  - name: nginx
    image: nginx
# annotations are similar to labels, it is key value pair, but not used as selectors. annotations are used to provision external resources to kuberentes. we keep external information build url, image registry, etc...annotations values can be 256char
